# Generated by Django 6.0.4 on 2026-04-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=202)),
                ('country', models.CharField(max_length=202)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/image/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=202)),
                ('color', models.CharField(max_length=101)),
                ('year', models.IntegerField(default=2020)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('probeg', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car/image/')),
                ('is_available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_app.brand')),
            ],
        ),
    ]
